# 1. Media
media:
    input: proto-plasma/public/images/news
    output: /images/news

# 2. Content
content:
    - name: news
      label: 部活動ニュース
      type: collection
      path: proto-plasma/src/content/news
      filename:
          template: "{year}-{month}-{day}-{create}.md"
          field: create

      format: yaml-frontmatter

      fields:
          - name: title
            label: タイトル
            type: string
            required: true
          - name: date
            label: 投稿日
            type: date
            required: true
          - name: description
            label: 概要
            type: text
          - name: image
            label: サムネイル画像
            type: image

          - name: body
            label: 本文
            type: code
            options:
                language: markdown

# 3. GitHub Actions
actions:
    - name: deploy-site
      label: サイトを更新して公開
      workflow: deploy.yml
